version: '3'
services:
  app:
    build: .
    volumes:
    - ~/.m2:/root/.m2
    ports:
     - "8080:8080"
    # command: mvn clean install
    # command: java -jar ./target/spring-boot-web-jsp-1.0.war
    
    # working_dir: /app
    #     volumes:
    # - .:/app
    # - ~/.m2:/root/.m2